# This file configures the build and deployment settings for Netlify.

[build]
  # This command will be run to build your site.
  command = "npm run build"
  # This is the directory that contains the built site.
  publish = "dist"
  # This is the directory for serverless functions.
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["lightningcss", "@babel/preset-typescript"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200